on: 
  push:
    branches:
      - main
      - dev

jobs:
  hellow-world:
    name: "hello world"
    runs-on: ubuntu-20.04
    steps:
      - name: Print 
        run:  "echo Welcome to the Github Actions workshop !"
  unit-test:
    name: "unit-test"
    runs-on: epitechcontent/epitest-docker
    - uses: actions/checkout@v3
    steps:
      - name: tests 
        run:  make tests_run
      - name: coverage 
        run:  make coverage
