on: 
  push:
    branches:
      - main
      - dev

jobs:
  hellow-world:
    name: "hello world"
    runs-on: ubuntu-20.04
    steps:
      - name: Print 
        run:  "echo Welcome to the Github Actions workshop !"
  
  unit-test:
    name: "unit-test"
    runs-on: epitechcontent/epitest-docker
    steps:
      - uses: actions/checkout@v3
      - run:  make tests_run
      - run:  make coverage
